// Generated by CoffeeScript 1.9.1
(function() {
  var FastBricks, expr, fastB, q, sql;

  sql = require('sql-bricks');

  FastBricks = require('fast-bricks');

  fastB = new FastBricks();

  fastB.loadConfig('database-config.cson');

  q = fastB.prototype.query;

  expr = sql.select().from("`user`");

  expr.log = true;

  q(expr, function(err, users) {
    var i, len, user;
    for (i = 0, len = users.length; i < len; i++) {
      user = users[i];
      console.log(user.id + " : " + user.username);
    }
  });

}).call(this);
